name: weather_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  get_it: ^7.2.0
  equatable: ^2.0.3
  intl: ^0.17.0
  geolocator: ^9.0.0
  connectivity_plus: ^2.3.5
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#5D8EEB"
  image: assets/images/splash.png


flutter:

  uses-material-design: true





  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
